// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Ef7Rc1Error.CompileModels
{
    public partial class MyDbContextModel
    {
        partial void Initialize()
        {
            var patient = PatientEntityType.Create(this);
            var role = RoleEntityType.Create(this);
            var roleClaim = RoleClaimEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var userClaim = UserClaimEntityType.Create(this);
            var userLogin = UserLoginEntityType.Create(this);
            var userRole = UserRoleEntityType.Create(this);
            var userToken = UserTokenEntityType.Create(this);

            RoleClaimEntityType.CreateForeignKey1(roleClaim, role);
            UserEntityType.CreateForeignKey1(user, patient);
            UserClaimEntityType.CreateForeignKey1(userClaim, user);
            UserLoginEntityType.CreateForeignKey1(userLogin, user);
            UserRoleEntityType.CreateForeignKey1(userRole, role);
            UserRoleEntityType.CreateForeignKey2(userRole, user);
            UserTokenEntityType.CreateForeignKey1(userToken, user);

            PatientEntityType.CreateAnnotations(patient);
            RoleEntityType.CreateAnnotations(role);
            RoleClaimEntityType.CreateAnnotations(roleClaim);
            UserEntityType.CreateAnnotations(user);
            UserClaimEntityType.CreateAnnotations(userClaim);
            UserLoginEntityType.CreateAnnotations(userLogin);
            UserRoleEntityType.CreateAnnotations(userRole);
            UserTokenEntityType.CreateAnnotations(userToken);

            AddAnnotation("ProductVersion", "7.0.0-rc.1.22426.7");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
