// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Ef7Rc1Error.CompileModels
{
    [DbContext(typeof(MyDbContext))]
    public partial class MyDbContextModel : RuntimeModel
    {
        static MyDbContextModel()
        {
            var model = new MyDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static MyDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
